# Generated by Django 2.1.1 on 2018-09-22 00:56

import backend.mixins.models
import backend.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import parler.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_changed_ts', models.DateTimeField(auto_now=True, verbose_name='Last changed at')),
                ('visible', models.BooleanField(default=True, verbose_name='Is visible?')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backend_category', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_changed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_backend_category', to=settings.AUTH_USER_MODEL, verbose_name='Last changed by')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_backend_category', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('parent', models.ManyToManyField(blank=True, related_name='_category_parent_+', to='backend.Category', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
            bases=(backend.mixins.models.AbstractNameSlugMixin, parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(db_index=True, max_length=1000, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=1008, null=True, verbose_name='Slug')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='backend.Category')),
            ],
            options={
                'verbose_name': 'Category Translation',
                'db_table': 'backend_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_changed_ts', models.DateTimeField(auto_now=True, verbose_name='Last changed at')),
                ('visible', models.BooleanField(default=True, verbose_name='Is visible?')),
                ('is_true', models.BooleanField(default=False, verbose_name='True?')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backend_claim', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'ordering': ('-is_true', '-last_changed_ts'),
            },
            bases=(backend.mixins.models.AbstractNameSlugMixin, parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClaimTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(db_index=True, max_length=1000, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=1008, null=True, verbose_name='Slug')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='backend.Claim')),
            ],
            options={
                'verbose_name': 'claim Translation',
                'db_table': 'backend_claim_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FactCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_changed_ts', models.DateTimeField(auto_now=True, verbose_name='Last changed at')),
                ('visible', models.BooleanField(default=True, verbose_name='Is visible?')),
                ('pub_date', models.DateTimeField(verbose_name='Publication Date')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('archive_url', models.URLField(blank=True, null=True, verbose_name='Archive URL')),
                ('screenshot', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=backend.models.get_upload_to, verbose_name='Screenshot')),
                ('lang', models.TextField(choices=[('en', 'English'), ('de', 'German')], default='en', verbose_name='Language')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backend_factcheck', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
            bases=(backend.mixins.models.AbstractNameSlugMixin, parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FactCheckTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(db_index=True, max_length=1000, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=1008, null=True, verbose_name='Slug')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='backend.FactCheck')),
            ],
            options={
                'verbose_name': 'fact check Translation',
                'db_table': 'backend_factcheck_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_changed_ts', models.DateTimeField(auto_now=True, verbose_name='Last changed at')),
                ('kind', models.CharField(choices=[('o', 'Original'), ('v', 'Variant'), ('t', 'Thumbnail'), ('d', 'Display'), ('s', 'Social Media')], default='o', max_length=1, verbose_name='Type')),
                ('credits', models.TextField(blank=True, null=True, verbose_name='Credits')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=backend.models.get_upload_to, verbose_name='Image')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backend_image', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_changed_ts', models.DateTimeField(auto_now=True, verbose_name='Last changed at')),
                ('visible', models.BooleanField(default=True, verbose_name='Is visible?')),
                ('category', models.ForeignKey(limit_choices_to={'parent__translations__name': 'CONTEXT'}, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.Category', verbose_name='Context')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backend_item', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_changed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_backend_item', to=settings.AUTH_USER_MODEL, verbose_name='Last changed by')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_backend_item', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'ordering': ('-last_changed_ts',),
                'get_latest_by': 'last_changed_ts',
                'abstract': False,
            },
            bases=(backend.mixins.models.AbstractNameSlugMixin, parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ItemTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(db_index=True, max_length=1000, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=1008, null=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='backend.Item')),
            ],
            options={
                'verbose_name': 'item Translation',
                'db_table': 'backend_item_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Occurence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_changed_ts', models.DateTimeField(auto_now=True, verbose_name='Last changed at')),
                ('visible', models.BooleanField(default=True, verbose_name='Is visible?')),
                ('pub_date', models.DateTimeField(verbose_name='Publication Date')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('archive_url', models.URLField(blank=True, null=True, verbose_name='Archive URL')),
                ('screenshot', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=backend.models.get_upload_to, verbose_name='Screenshot')),
                ('lang', models.TextField(choices=[('en', 'English'), ('de', 'German')], default='en', verbose_name='Language')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backend_occurence', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurences', to='backend.Item')),
                ('last_changed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_backend_occurence', to=settings.AUTH_USER_MODEL, verbose_name='Last changed by')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_backend_occurence', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
            bases=(backend.mixins.models.AbstractNameSlugMixin, parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OccurenceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(db_index=True, max_length=1000, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=1008, null=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='backend.Occurence')),
            ],
            options={
                'verbose_name': 'occurence Translation',
                'db_table': 'backend_occurence_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_changed_ts', models.DateTimeField(auto_now=True, verbose_name='Last changed at')),
                ('visible', models.BooleanField(default=True, verbose_name='Is visible?')),
                ('url', models.URLField()),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'parent__translations__name': 'SOURCE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='backend.Category', verbose_name='Category')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backend_source', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_changed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_backend_source', to=settings.AUTH_USER_MODEL, verbose_name='Last changed by')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_backend_source', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
            },
            bases=(backend.mixins.models.AbstractNameSlugMixin, parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SourceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(db_index=True, max_length=1000, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=1008, null=True, verbose_name='Slug')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='backend.Source')),
            ],
            options={
                'verbose_name': 'Source Translation',
                'db_table': 'backend_source_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_changed_ts', models.DateTimeField(auto_now=True, verbose_name='Last changed at')),
                ('visible', models.BooleanField(default=True, verbose_name='Is visible?')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='backend.Category', verbose_name='Category')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backend_tag', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_changed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_backend_tag', to=settings.AUTH_USER_MODEL, verbose_name='Last changed by')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_backend_tag', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('parent', models.ManyToManyField(blank=True, related_name='_tag_parent_+', to='backend.Tag', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
            bases=(backend.mixins.models.AbstractNameSlugMixin, parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TagTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(db_index=True, max_length=1000, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=1008, null=True, verbose_name='Slug')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='backend.Tag')),
            ],
            options={
                'verbose_name': 'Tag Translation',
                'db_table': 'backend_tag_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_changed_ts', models.DateTimeField(auto_now=True, verbose_name='Last changed at')),
                ('kind', models.CharField(choices=[('o', 'Original'), ('v', 'Variant'), ('t', 'Thumbnail'), ('d', 'Display'), ('s', 'Social Media')], default='o', max_length=1, verbose_name='Type')),
                ('credits', models.TextField(blank=True, null=True, verbose_name='Credits')),
                ('video', models.FileField(blank=True, null=True, upload_to=backend.models.get_upload_to, verbose_name='Video File')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video URL')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backend_video', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_assets', to='backend.Item')),
                ('last_changed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_backend_video', to=settings.AUTH_USER_MODEL, verbose_name='Last changed by')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_backend_video', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='occurence',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurences', to='backend.Source'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(limit_choices_to={'category__translations__name': 'DESCRIPTIVE'}, related_name='items', to='backend.Tag'),
        ),
        migrations.AddField(
            model_name='image',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_assets', to='backend.Item'),
        ),
        migrations.AddField(
            model_name='image',
            name='last_changed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_backend_image', to=settings.AUTH_USER_MODEL, verbose_name='Last changed by'),
        ),
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_backend_image', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='factcheck',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factchecks', to='backend.Item'),
        ),
        migrations.AddField(
            model_name='factcheck',
            name='last_changed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_backend_factcheck', to=settings.AUTH_USER_MODEL, verbose_name='Last changed by'),
        ),
        migrations.AddField(
            model_name='factcheck',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_backend_factcheck', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='factcheck',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factchecks', to='backend.Source'),
        ),
        migrations.AddField(
            model_name='claim',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='backend.Item', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='claim',
            name='last_changed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_backend_claim', to=settings.AUTH_USER_MODEL, verbose_name='Last changed by'),
        ),
        migrations.AddField(
            model_name='claim',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_backend_claim', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterUniqueTogether(
            name='tagtranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='sourcetranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='occurencetranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='itemtranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='factchecktranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='claimtranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='categorytranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
