# Generated by Django 2.1.1 on 2018-09-29 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180929_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factcheck',
            name='lang',
            field=models.ForeignKey(limit_choices_to={'category__translations_name': 'LANGUAGE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Tag', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='occurence',
            name='lang',
            field=models.ForeignKey(limit_choices_to={'category__translations_name': 'LANGUAGE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Tag', verbose_name='Language'),
        ),
    ]
